language: python
python:
- '3.6'
install:
- python setup.py install
script:
- python setup.py test
deploy:
  provider: pypi
  user: ewhitmire
  password:
    secure: s8Bwavrvj5c3O8eqyW1GOy/SorfzbOuB5NL64H98ZZUmsq1JOmPlpNqCT1G337VGP/ShwRrNkGioYJgwO57sZtwewDepGOE6CmMnP6MRRHKsGItQWKKYu3jss3mgsCsIcF+pIPvhi8KF4jKud8zjHzjKUVip8mCnUjlS9Rl22/UjmSGQqDfFMZssKsNxlZ6yXlhTZfpR7RerFwCwMwIs4vnMZXcceR3/slOpxq/t5ffAFrv7hdMla5/CSgUNHo8339Aon4DVhhQ+poTKmdoOyjlte7Vuu6d8BKiDbixdTH7iQzISetwpYx1JbLM1XhKvxrOIS7dX6uEm0V3UUu/MnGGjV8kfq+Q1X0xgXNQe7WIboM+HcsZ78+5H2/GG1cI1h32IH/VoPvNMviBHbu5WtbYcl+WQwPvjEHizwwdN19oQ0MRwcouLp+KaC2lKebqHg0holE2fxBrWs86C9ADYdddwO/Zh+4UhK886tYGGm7GCwH4AJ5VAfFC6HM8WwabO5EuAs8+XnWgocHut2uhbAP69L/xDCnXk9I0Ta/dwuk3UBVeNi4HDH08Z71P4Se+1AbN06rJw5/pjUPKmVpEJ7Yq1NgfaIVfy0EwEb/KlYGw/FI1jdxhiJTFD2cDpYsvQbMR/wWdPnkqPeM9rTkqLPDwy6M+TgkncsfKY5ruduBA=
  on:
    tags: true
  distributions: "sdist bdist_wheel"